# Automatic Minecraft update section
[updates]

# Version directory names, in the order they should be progressed through
# They do not need to be version numbers, the minecraft version will be extracted from the packwiz pack.toml
versions = [
    #"1.0", # 1.0 and 1.1 do not offer an official server download anymore
    #"1.1",
    "1.2.5",
    "1.3.2",
    "1.4.7",
    "1.5.2",
    "1.6.4",
    "1.7.10",
    "1.8.9",
    "1.9.4",
    "1.10.2",
    "1.11.2",
    "1.12.2",
    "1.13.2",
    "1.14.4",
    "1.15.2",
    "1.16.5",
    "1.17.1",
    "1.18.2",
    "1.19.4",
]

# Run every x minutes, ensure this is enough time to start the server and finish world conversion, 1440 min = 24 hours
interval = 1440

# Starting time of day, in 24 hour format
start_time = "04:00"

# Major version upgrades for which switching java version is recommended
# Upgrading java can only be automated on the server, players will need to update their client manually
# Players may also choose to skip the java compatibility check in their clients and always use the latest version,
# but this can cause instability and crashes

# Most bottom image that is <= the given minecraft version will be used
[[upgrades]]
minecraft_version = "1.0"
server_image = "itzg/minecraft-server:java8-multiarch"

[[upgrades]]
minecraft_version = "1.17"
server_image = "itzg/minecraft-server:latest"
