# Set minimum logging level to display, acceptable values: DEBUG, INFO, WARNING, ERROR, CRITICAL
verbosity = "INFO"

# Automatic Minecraft update section
[updates]

# Run every x minutes, ensure this is enough time to stop, download, start the server and finish world conversion
# 1440 min = 24 hours
interval = 1440

# Starting time of day, in 24 hour format
start_time = "04:00"

# List of variants, in the order they should be progressed through
# Attributes will be inherited from the previous variants, meaning only the attributes that change need to be specified

# name = Directory name inside packwiz directory, does not need to be a version number
# server_image = Docker image to use for the server
# server_type = Server type, default: "VANILLA"
# server_version = Minecraft version for just the server, default: "packwiz" - version from packwiz pack.toml

[[variant]]
pack = "1.0"
server_image = "itzg/minecraft-server:java8-multiarch"
server_type = "VANILLA"
server_version = "packwiz"

[[variant]]
pack = "1.1"

[[variant]]
pack = "1.2.5"

[[variant]]
pack = "1.3.2"

[[variant]]
pack = "1.4.7"

[[variant]]
pack = "1.5.2"

[[variant]]
pack = "1.6.4"

[[variant]]
pack = "1.7.10"

[[variant]]
pack = "1.8.9"

[[variant]]
pack = "1.9.4"

[[variant]]
pack = "1.10.2"

[[variant]]
pack = "1.11.2"

[[variant]]
pack = "1.12.2"

[[variant]]
pack = "1.13.2"

[[variant]]
pack = "1.14.4"

[[variant]]
pack = "1.15.2"

[[variant]]
pack = "1.16.5"

[[variant]]
pack = "1.17.1"
server_image = "itzg/minecraft-server:latest"

[[variant]]
pack = "1.18.2"

[[variant]]
pack = "1.19.4"


# Automatically update a stack on your portainer instance
# Requires setting API key in secrets.toml (copy the secrets.toml.example file)
[portainer]
enable = false
hostname = "your-portainer-host.com" # omit "https://", it will be included automatically (your server must use https)
stack_name = "minecraft-timeline-server" # Name of EXISTING stack, create a dummy stack first
