# Set minimum logging level to display, acceptable values: DEBUG, INFO, WARNING, ERROR, CRITICAL
verbosity = "INFO"

# Automatic Minecraft update section
[updater]

# Timeline config files to parse and switch between variants from, in the order of array elements
timelines = ["timeline-release-bukkit-paper", "timeline-custom"]

# Run every x minutes, ensure this is enough time to stop, download, start the server and finish world conversion
# 1440 min = 24 hours
interval = 1440

# Starting time of day, in 24 hour format OR "now" to immediately start
start_time = "04:00"


# Save timeline progress in order to continue without starting from the beginning
[updater.save]
enable = true
path = "save.txt"

# Should the first update be the same as where it stopped or should it skip the last update?
# true, false or "auto" (true if start_time is "now")
repeat_after_load = "auto"

# Should the save file remain after the last update, blocking future restarts?
keep = true


# Automatically copy pack into a target directory, for example into your webserver
[packwiz]
enable = true
output_path = "packwiz_out"


# Automatically update a stack on your portainer instance
# Requires setting API key in secrets.toml (copy the secrets.toml.example file)
[portainer]
enable = false
hostname = "your-portainer-host.com" # omit "https://", it will be included automatically (your server must use https)
stack_name = "minecraft-timeline-server" # Name of EXISTING stack, create a dummy stack first
