version: '3.5'
services:
    minecraft-timeline-server:
        image: {server_image}

        environment:
            # Timezone identifiers: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
            #- TZ=Etc/UTC

            # Run as specific user and group id, to avoid permission issues
            #- UID=1000
            #- GID=1000

            # Change this to TRUE if you accept the minecraft EULA
            - EULA=FALSE

            # Server type
            - TYPE={server_type}
            - VERSION={server_version}

            # Start the server with --forceUpgrade to ensure the whole world is converted every upgrade
            # If disabled, very old unconverted chunks may not be able to load in modern versions
            - EXTRA_ARGS="--forceUpgrade"

            # Use this if you use packwiz to add additional content, not just to specify minecraft versions
            #- PACKWIZ_URL=http://localhost/pack.toml

            # Performance
            - MEMORY=4G
            - USE_AIKAR_FLAGS=TRUE

        ports:
            - '25565:25565'

        volumes:
            # Change this to your own path
            - '/minecraft_data:/data'

        restart: "unless-stopped"
