# Release timeline - Vanilla gameplay, the latest patch of every major version since inclusive 1.0

# For details on variant config settings see timeline-custom.toml

[[variants]]
pack = "1.0"
server_image = "itzg/minecraft-server:java8-multiarch"

# Use Bukkit for 1.0, 1.1 since there is no official vanilla server download anymore
server_type = "BUKKIT"
server_version = "1.0.0-SNAPSHOT"

# Healthchecks on 1.0 - 1.3, don't seem to work and just end up spamming the logs
server_additional_envs = { DISABLE_HEALTHCHECK = "TRUE" }

[[variants]]
pack = "1.1"
server_type = "BUKKIT"
server_version = "1.1-R5-SNAPSHOT"

[[variants]]
pack = "1.2.5"
server_type = "VANILLA"
server_version = "packwiz"

[[variants]]
pack = "1.3.2"

[[variants]]
pack = "1.4.7"
server_additional_envs = { } # Clear envs, re-enabling healthchecks

[[variants]]
pack = "1.5.2"

[[variants]]
pack = "1.6.4"

[[variants]]
pack = "1.7.10"

[[variants]]
pack = "1.8.9"

[[variants]]
pack = "1.9.4"

[[variants]]
pack = "1.10.2"

[[variants]]
pack = "1.11.2"

[[variants]]
pack = "1.12.2"

[[variants]]
pack = "1.13.2"

[[variants]]
pack = "1.14.4"

[[variants]]
pack = "1.15.2"

[[variants]]
pack = "1.16.5"

[[variants]]
pack = "1.17.1"
server_image = "itzg/minecraft-server:latest"

[[variants]]
pack = "1.18.2"

[[variants]]
pack = "1.19.4"
