# Release timeline - But with optimized server software and plugin support
# Using Bukkit for 1.0 to 1.7.10 and Paper for 1.8.8/9+

# Mostly vanilla but Paper also fixes what it considers "gameplay and mechanics inconsistencies" and can break certain
# contraptions

# For details on variant config settings see timeline-custom.toml

[[variants]]
pack = "1.0"
server_image = "itzg/minecraft-server:java8-multiarch"

server_type = "BUKKIT"

# Bukkit needs specific build names
server_version = "1.0.0-SNAPSHOT"

# Healthchecks on 1.0 - 1.3, don't seem to work and just end up spamming the logs
server_additional_envs = { DISABLE_HEALTHCHECK = "TRUE" }

[[variants]]
pack = "1.1"
server_version = "1.1-R5-SNAPSHOT"

[[variants]]
pack = "1.2.5"
server_version = "1.2.5-R5.1-SNAPSHOT"

[[variants]]
pack = "1.3.2"
server_version = "1.3.2-R2.1-SNAPSHOT"

[[variants]]
pack = "1.4.7"
server_version = "1.4.7-R1.1-SNAPSHOT"
server_additional_envs = { } # Clear envs, re-enabling healthchecks

[[variants]]
pack = "1.5.2"
server_version = "1.5.2-R1.0"

[[variants]]
pack = "1.6.4"
server_version = "1.6.4-R2.0"

[[variants]]
pack = "1.7.10"
server_version = "1.7.10-R0.1-20140808.005431-8"


[[variants]]
pack = "1.8.9"

# Switch to paper
server_type = "PAPER"

# Paper doesn't have a 1.8.9 version but 1.8.8 is compatible with 1.8.9
server_version = "1.8.8"

[[variants]]
pack = "1.9.4"

# Paper doesn't need special build versions, switch back to using version from packwiz
server_version = "packwiz"

[[variants]]
pack = "1.10.2"

[[variants]]
pack = "1.11.2"

[[variants]]
pack = "1.12.2"

[[variants]]
pack = "1.13.2"

[[variants]]
pack = "1.14.4"

[[variants]]
pack = "1.15.2"

[[variants]]
pack = "1.16.5"

[[variants]]
pack = "1.17.1"
server_image = "itzg/minecraft-server:latest"

[[variants]]
pack = "1.18.2"

[[variants]]
pack = "1.19.4"
